### ISSUE TITLE
some sensors are missing

### ISSUE THREAD

**Issue by bandi72** [lavinir/hassio-onedrive-backup#11]
Hi
I don't know why but there are no LAST and BACKUP IN sensors in my installation. Installation on Debian.

![onedrive](https://user-images.githubusercontent.com/119104218/204081354-24bba7f7-64c2-4870-9da1-09b25635cc69.jpg)

Regards
Marcin

**Comment by lavinir** [comment]
What view is this ? There is one sensor entity for the FreeSpace and another Sensor for the rest of the backup data which should be with this id **sensor.onedrivebackup**. 

The additional data is added as attributes to this sensor. Could you share the entity details similarly to this screenshot:
![onesensor](https://user-images.githubusercontent.com/56975945/204130363-21f829fe-a6c6-4bc0-a3cc-d7a4d97ef1b5.png)

Is **Backups Stale** something you added yourself ?

**Comment by bandi72** [comment]
It's ok here. But I don't have a sensor to pull it to the desktop like in your project screenshot.
![onedrive2](https://user-images.githubusercontent.com/119104218/204132764-7499c9e1-709c-4146-a710-4038833a6f1d.jpg)
![onedrive3](https://user-images.githubusercontent.com/119104218/204132765-2c1a0a10-c3e1-4cdb-b19a-ba64ef535271.jpg)


Backups Stale:
I added a sensor from google by mistake :-)

**Comment by lavinir** [comment]
So that's just a frontend thing. Since there aren't separate entities for this you just need to show the attribute in your dashboard instead. There are a few ways to do this but you have native support in the **Entities** card by using an [Attribute Row Element](https://www.home-assistant.io/dashboards/entities/#attribute) which is what I used in my setup.

**Comment by bandi72** [comment]
Thank you very much

Maybe someone will like it:
configuration.yaml

```
- platform: template
  sensors:
      onedrive_last_local:
      friendly_name: 'Last Local backup date'
      value_template: "{{ state_attr('sensor.onedrivebackup', 'Last Local backup date')}}"
```
