### ISSUE TITLE
Plugin Crashes after some time

### ISSUE THREAD

**Issue by FabianClemenz** [lavinir/hassio-onedrive-backup#240]
Hello,

After installing and configuration, the plugin stops working at some time and I have to manually start it. But then I stays in "initializing" mode. The last time I uninstalled the plugin an reinstalled it - but that is not applicable for every day...

what can I do here?

**Comment by jterfehr2000** [comment]
Same problem.  Shuts down for no reason..notify on error doesnt fire.  I only find out if i go check on it.

**Comment by FabianClemenz** [comment]
Yes exactly the same happens to me

**Comment by Nilogax** [comment]
Same here - just stops with no error logged. FWIW I've built an automation to notify me if the last backup is out of date - I use daily backups but that part is easy to change

```yaml
alias: OneDrive Backup - alert if stale
description: ""
mode: single
triggers:
  - hours: /12
    trigger: time_pattern
conditions:
  - condition: template
    value_template: >-
      {%if states('sensor.onedrivebackup') is defined %}

      {{state_attr('sensor.onedrivebackup', 'Last OneDrive backup date') |
      as_timestamp <  (now() - timedelta(hours=25)) | as_timestamp }} 

      {% else %}

      {{true}}

      {%endif%}
actions:
  - metadata: {}
    data:
      message: OneDrive backup is stale
    action: notify.mobile_app_pixel_8
```
