### ISSUE TITLE
Cannot edit entities

### ISSUE THREAD

**Issue by felipecrs** [lavinir/hassio-onedrive-backup#82]
Hi, thanks a lot for this awesome add-on.

However, it adds some entities to Home Assistant in which I cannot edit. For example, I would like to:

- Fix its name and ID
- Hide it so it does not appear in my dashboard automatically

And there is no way to disable them either. The settings panel says I cannot edit them because they do not have an unique id set.

**Comment by lavinir** [comment]
Hi, 

Right, I don't think there is a way for me to give them a unique id as this is done through and add-on and not an integration. 
Why is it automatically added to your dashbaord ? Is this the default dash ? Wouldn't that be the case for all other entities as well?

For changing the displayname in the dashboard you can still do that in the lovelace cards configuration. What exactly are you trying to achieve ?

**Comment by lavinir** [comment]
It is possible but I'm not sure of the big downside here. The entities are valuable for dashboard integration and automations.
If you remove them from your dashboard, do they 'bother' you in anyother way ?

**Comment by felipecrs** [comment]
But there is no way to remove them from my dashboard, unless I migrate my dashboard to a manually managed dashboard.

Also, maybe this is not applicable, but entities which are not hidden are automatically shared with the Google Assistant.

But I like the existence of these entities. As you say, they can be useful. What I don't like is the fact that I can't hide them.

**Comment by lavinir** [comment]
I understand, not sure I have a good solution for this as I am not aware of a way to have a unique id for an entity state set from an Addon. 
I will consider adding an option to disable entity integration though.

Personally I'd recommend you don't use a managed dashboard for many reasons but that's just a personal preference :)

**Comment by felipecrs** [comment]
That's a good suggestion, and I can apply it.

May I know which API/method you are using to create the entities? I can follow up with Home Assistant to check if they plan to add support for setting unique IDs.

**Comment by lavinir** [comment]
sure. 
Using the _states/< entityid >_ call. See https://developers.home-assistant.io/docs/api/rest/

**Comment by felipecrs** [comment]
I see. As you said, there is no way to set unique_id in that case. =/

**Comment by felipecrs** [comment]
I found a solution for this problem!

```yaml
# configuration.yaml

template:
  - sensor:
      - name: onedrivebackup
        unique_id: 7afef23f6f37
        state: "{{ None }}"
      - name: onedrivefilesync
        unique_id: 588c08bc024c
        state: "{{ None }}"
      - name: onedrivefreespace
        unique_id: 9d89d14524a5
        state: "{{ None }}"
```

The entities must first exist. You can create dummy entities with the above.

Then, restart Home Assistant.

Now, the entities can be edited and the add-on will continue to publish status to it normally

You can change the entity name (from the UI, not from the YAML), hide it, change the icon, pretty much everything.

However, do NOT change the entity id. If you do, the add-on will create its own entities again.
